### ISSUE TITLE
Repository description links to alpha

### ISSUE THREAD

**Issue by andys8** [Punie/elm-reader#5]
Repository links to https://alpha.elm-lang.org/packages/Punie/elm-reader/latest/

![image](https://user-images.githubusercontent.com/13085980/48707928-4c0f6580-ec01-11e8-9bef-9f30910cbf4a.png)

Fix with: https://package.elm-lang.org/packages/Punie/elm-reader/latest/

**Comment by Punie** [comment]
Good catch, thank you!
For some reason I did not get a notification from github for this issue so sorry for the delay.
